### ISSUE TITLE
[BUG] - [VERY LITTLE :-] - use - for snake, not _

### ISSUE THREAD

**Issue by Lajule** [30-seconds/30-seconds-of-python#114]
Hi,
First congratulation for this great work !!!

There is a little mistake in the snake case snippet, it mention '_' in examples results but i think it might be a '-', take a look to following lines :

- https://github.com/30-seconds/30-seconds-of-python/blame/master/snippets/snake.md#L21
- https://github.com/30-seconds/30-seconds-of-python/blame/master/snippets/snake.md#L22
- https://github.com/30-seconds/30-seconds-of-python/blame/master/snippets/snake.md#L23
- https://github.com/30-seconds/30-seconds-of-python/blame/master/snippets/snake.md#L24

### Expected Snippet Behavior

'-' in  examples results

### Current Snippet Behavior

'_'  in  examples results

### Possible Solution

'-' in  examples results

Best regards,
Julien

**Comment by rfezzani** [comment]
Hi all, I also noticed that the camel case example is not working:

```python
>>> snake('camelCase')
'camelcase'
```

**Comment by Chalarangelo** [comment]
Maybe transforming the original JS regexp didn't work for those. I will see what I can do or you can open a PR with a proposal to fix the code.
