### ISSUE TITLE
Wrong Definition

### ISSUE THREAD

**Issue by Natgho** [30-seconds/30-seconds-of-python#123]
https://github.com/30-seconds/30-seconds-of-python#filter_non_unique

Non unique definition is return "non-unique values in a list." but function content return only unique values.
It must change function content to:
```python
def filter_non_unique(lst):
  return [item for item in lst if lst.count(item) < 1]
```
or header name must change to "filter_unique".

**Comment by Chalarangelo** [comment]
Thanks for the heads up, you can submit a PR with the recommended fix and we'll take it from there.
