### ISSUE TITLE
[BUG] Intersection Snippet change

### ISSUE THREAD

**Issue by robotenique** [30-seconds/30-seconds-of-python#124]
It's not properly a bug, but rather a question/improvement.

In snippet `intersection` (https://github.com/30-seconds/30-seconds-of-python#intersection
), would't it be better to use sets functionality directly instead of doing a list comprehension?

### Possible Solution

```python
def intersection(a, b):
  _a, _b = set(a), set(b)
  return list(_a & _b)
```

**Comment by Chalarangelo** [comment]
Thanks for the suggestion, feel free to open a PR with this!

**Comment by robotenique** [comment]
Will do
