### ISSUE TITLE
[FEATURE] Improve filter_unique and filter_non_unique running time

### ISSUE THREAD

**Issue by mx-psi** [30-seconds/30-seconds-of-python#170]
The [filter_non_unique](https://www.30secondsofcode.org/python/s/filter-non-unique) and [filter_unique](https://www.30secondsofcode.org/python/s/filter-unique) snippets currently have a quadratic running time;  in both cases they count each item in the original list. This can be improved to linear time by using a counter from [the `collections` module](https://docs.python.org/3/library/collections.html#collections.Counter) (at the expense of linear space).

### Improvement of filter_unique

```python
from collections import Counter


def filter_unique(lst):
  counter = Counter(lst)
  return [item for item, count in counter.items() if count > 1]
```

### Improvement of filter_non_unique

```python
from collections import Counter


def filter_non_unique(lst):
  counter = Counter(lst)
  return [item for item, count in counter.items() if count == 1]
```

**Comment by Chalarangelo** [comment]
If you can PR these changes along with their explanations, I'd be glad to merge them. Thanks for the feedback!
