### ISSUE TITLE
[FEATURE] Using defaultdict in *group_by* implementation

### ISSUE THREAD

**Issue by geekypandey** [30-seconds/30-seconds-of-python#201]
The current implementation of group_by loops *twice* over the *lst*, which significantly reduces the speed when working with large data. Instead using *defaultdict* will make it possible to loop over the *lst* only once.
 
**Current implementation:**
```python
def group_by(lst, fn):
    return {key: [el for el in lst if fn(el] == key] for key in map(fn, lst)}
```

**Suggested implementation:**
```python
from collections import defaultdict

def group_by(lst, fn):
    d = defaultdict(list)
    for el in lst:
        d[fn(el)].append(el)
    return d
```

**Comment by zhangfelix** [comment]
Yeah, it looks more efficient that way. The python official website also gives a similar [example](https://docs.python.org/3.6/library/collections.html#defaultdict-examples). 

And `defaultdict` can also be used in the implementation of `count_by`.

**Current implementation:**

```py
def count_by(arr, fn=lambda x: x):
  key = {}
  for el in map(fn, arr):
    key[el] = 1 if el not in key else key[el] + 1
  return key
```

**Suggested implementation:**

```py
from collections import defaultdict

def count_by(lst, fn):
  d = defaultdict(int)
  for el in lst:
    d[fn(el)] += 1
  return d
```

**Comment by Lattay** [comment]
Just want to point out that this change is more important that said.
As I explain in #213 the initial implementation does not loop twice over the elements, it loops n times over all elements, which would be dramatic for as few as 1000 elements.
