### ISSUE TITLE
[BUG] syntax error in implementation of filter_non_unique

### ISSUE THREAD

**Issue by geekypandey** [30-seconds/30-seconds-of-python#202]
A small syntax issue in the implementation of [filter_non_unique](https://github.com/30-seconds/30-seconds-of-python/blob/master/snippets/filter_non_unique.md).

```python
from collections import Counter

def filter_non_unique(lst):
    return [item for item, count in counter = Counter(lst).items() if count == 1]
```

I think we could implement the similar thing in python3.8 using the *Walrus* operator ( **:=**).

**Comment by guojinyu12** [comment]
In 5.7 of Python Documentation.
Note that in Python, unlike C, assignment inside expressions must be done explicitly with the walrus operator :=. This avoids a common class of problems encountered in C programs: typing = in an expression when == was intended.
