### ISSUE TITLE
[QUESTION]Whether to pay attention to parameter checking and exception handling

### ISSUE THREAD

**Issue by zhangfelix** [30-seconds/30-seconds-of-python#207]
Should we pay attention to parameter checking and exception handling, or should we focus more on showing a possible idea for solving the problem?

For example in [lcm.md](https://github.com/30-seconds/30-seconds-of-python/blob/master/snippets/lcm.md), the current implementation has the potential to cause a divide by zero exception.

Also, by definition, lcm should be a positive integer. However, the current implementation may result in the return of a negative number.

**Current implementation**

```py
from functools import reduce
from math import gcd

def lcm(numbers):
  return reduce((lambda x, y: int(x * y / gcd(x, y))), numbers)
```

**Comment by Chalarangelo** [comment]
Hey there! 

The decision to not check for errors and edge cases was made a long time ago when we started these projects and the reason behind it was to keep them simple and showcase interesting techniques and ways of thinking. All snippets expect the user to have a basic understanding of the problem, the language and potential errors that might occur, thus we are not adding exception handling or parameter checking to snippets.

Thank you.
