### ISSUE TITLE
[BUG] kebab function is not working for some strings

### ISSUE THREAD

**Issue by zhangfelix** [30-seconds/30-seconds-of-python#212]
Current implementation of [kebab](https://github.com/30-seconds/30-seconds-of-python/blob/master/snippets/kebab.md) function is not working for strings like 'camelCase'.

**Current implementation**

```py
from re import sub

def kebab(s):
  return sub(
    r"(\s|_|-)+","-",
    sub(
      r"[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+",
      lambda mo: mo.group(0).lower(), s))

kebab('camelCase') # 'camel-case'
kebab('some text') # 'some-text'
kebab('some-mixed_string With spaces_underscores-and-hyphens') # 'some-mixed-string-with-spaces-underscores-and-hyphens'
kebab('AllThe-small Things') # "allthe-small-things"
```

Actually, `kebab('camelCase')` returns `'camelcase'`, and `kebab('AllThe-small Things')` returns `'all-the-small-things'`

The first `re.sub(pattern, repl, string, count=0, flags=0)` function can find out all the words. But the `repl` function(`lambda mo: mo.group(0).lower()`) add nothing to separate them, just changes those words to lower case. 

Inspired by [snake](https://github.com/30-seconds/30-seconds-of-python/blob/master/snippets/snake.md) function, I think kebab can be modified like follows:

```py
from re import sub

def kebab(s):
  return '-'.join(
    sub(r"(\s|_|-)+"," ",
    sub(r"[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+",
    lambda mo: ' ' + mo.group(0).lower(), s)).split())
```

All the examples works well:

```py
>>> kebab('camelCase') # 'camel-case'
'camel-case'
>>> kebab('some text') # 'some-text'
'some-text'
>>> kebab('some-mixed_string With spaces_underscores-and-hyphens') # 'some-mixed-string-with-spaces-underscores-and-hyphens'
'some-mixed-string-with-spaces-underscores-and-hyphens'
>>> kebab('AllThe-small Things') # "all-the-small-things"
'all-the-small-things'
```

**Comment by Trinityyi** [comment]
Thanks for the heads up. Fix deployed. 👍
