### ISSUE TITLE
Can I add code snippets for text processing?

### ISSUE THREAD

**Issue by sainimohit23** [30-seconds/30-seconds-of-python#330]
Hi, I primarily work on NLP. So, I do a lot of text processing using built-in methods and re module. Can I contribute code snippets of text processing?

**Comment by Trinityyi** [comment]
Thanks for the idea. However, text processing might require a lot more explaining than we can do in 30 seconds, as the user might not be familiar with many different concepts that they should understand before diving into code and implementation details showcased in a snippet.

**Comment by sainimohit23** [comment]
@Trinityyi I am not talking about full-fledged text processing. I am interested in simple stuff that we usually google while programming.
