### ISSUE TITLE
Can I add a string_chunk

### ISSUE THREAD

**Issue by PotatoK123** [30-seconds/30-seconds-of-python#356]
It'll separate a string into smaller strings of n long and place into a list.

Maybe duplicate of
https://github.com/30-seconds/30-seconds-of-python/blob/master/snippets/chunk.md
? (instead of lists its strings)

(If it gets accepted)
Also, should it be called chunk_string or string_chunk or something else?

**Comment by gurukiran07** [comment]
Hey, [`chunk.md`](https://github.com/30-seconds/30-seconds-of-python/blob/master/snippets/chunk.md) works with strings too.

```python
chunk("abcdefgh", 2)
['ab', 'cd', 'ef', 'gh']
```

**Comment by PotatoK123** [comment]
oh damn

**Comment by PotatoK123** [comment]
anything else I could add?

**Comment by Chalarangelo** [comment]
As @gurukiran07 said, `chunk` already covers this case.
