### ISSUE TITLE
time complexity improv of frequencies.md

### ISSUE THREAD

**Issue by gurukiran07** [30-seconds/30-seconds-of-python#362]
In [`frequencies.md`](https://github.com/30-seconds/30-seconds-of-python/blob/master/snippets/frequencies.md), the time complexity is `O(n^2)`. `list.count()`'s complexity is `O(n)`, using `list.count` `n` times, making it quadratic time.
```py
# Current implementation.
def frequencies(lst):
  return dict((k, lst.count(k)) for k in lst)
```
We can use [`collections.Counter`](https://docs.python.org/3.9/library/collections.html#collections.Counter) which does it in `O(n)`.

```py
from collections import Counter
def frequencies(lst):
    return Counter(lst)
```
Using `collection.defaultdict`
```py
from collections import defaultdict
def frequencies(lst):
    d = defaultdict(int)
    for v in lst:
        d[v]+=1
    return d
```

```py
# pure python implementation
def frequencies(lst):
    d = dict()
    for v in lst:
        d[v] = d.get(v, 0) + 1  # d.setdefault(v, 0)
    return d
```
All the above mentioned are `O(n)` run time functions. Please select whichever you see fit.

**Comment by Trinityyi** [comment]
That's an accurate observation. `Counter` might be a bit too much of a black box for some readers, but you might be onto something with the `defaultdict` implementation. Only thing I'd change in that one would be the `return` statement to wrap the result in a `dict()` call. Other than that, I think that's a valid way to improve the snippet, so feel free to PR it.

**Comment by Navaneethnanda** [comment]
really great improvement

**Comment by gurukiran07** [comment]
> Counter might be a bit too much of a black box for some readers @Trinityyi 
Yes, agreed.
> Only thing I'd change in that one would be the return statement to wrap the result in a dict() call
Okay, will do.

And I made a partial list of questions(will prepare the whole list in a day or two) that are frequently asked on StackOverflow, should I post the list in another issue where we can scrutinize the proposed questions?

**Comment by Chalarangelo** [comment]
@gurukiran07 Sure, you can open an issue and we might start tackling them one by one.
