### ISSUE TITLE
improvement in fibbonocci code

### ISSUE THREAD

**Issue by Navaneethnanda** [30-seconds/30-seconds-of-python#363]
time complexity can be reduced by updating the length at every step instead of calculating it every single time and the function is returning a list of length n+1 instead of n.

here is the improvement.
```py
def fibonacci(n):
  if n <= 0:
    return [0]

  sequence = [0, 1]
  sequenceLength=2
  while sequenceLength < n:
    next_value = sequence[sequenceLength - 1] + sequence[sequenceLength - 2]
    sequence.append(next_value)
    sequenceLength+=1

  return sequence
```

**Comment by Trinityyi** [comment]
Thanks for the idea. However, any small performance overhead that the current implementation has, it makes up in terms of readability. Also, the current result is correct. No need to make any changes to the snippet, will leave as-is for now,
