### ISSUE TITLE
Selecting a random element from a given sequence

### ISSUE THREAD

**Issue by random-Amanda** [30-seconds/30-seconds-of-python#387]
Hi, I would like to add a PR
Selecting a random element from a given sequence
seq = ['a', 'b', 'c', 'd']
output -> 'c' # selected randomly each time.

**Comment by Chalarangelo** [comment]
Please don't. If you took the time to search the website, you'd find out that [sample](https://www.30secondsofcode.org/python/s/sample) already accomplishes that. Cheers.
