### ISSUE TITLE
Improvement in time complexity.

### ISSUE THREAD

**Issue by Navaneethnanda** [30-seconds/30-seconds-of-python#389]
In [`most_frequent.md`](https://github.com/30-seconds/30-seconds-of-python/blob/master/snippets/most_frequent.md) the complexity of the code is O(n^2). Upon calculating frequency and then retrieving max time complexity can be reduced to O(n) and it adds to code readability.

```py
#current code
def most_frequent(list):
  return max(set(list), key=list.count)
```

using defaultdict from collections module for calculating frequency and then finding the key of dictionary with max value gives us the most frequent element in O(n).

```py

from collections import defaultdict

def most_frequent(lst):
  freqency = defaultdict(int)
  for val in lst:
    freqency[val] += 1
  return max(freqency, key=lambda x:freqency[x])#or max(freqency, key=freqency.get)
```
please let know your opinion.

**Comment by Chalarangelo** [comment]
No, thanks. The current implementation is far more readabale as-is.
