### ISSUE TITLE
Removed the hacktoberfest label? :/

### ISSUE THREAD

**Issue by alanpcs** [30-seconds/30-seconds-of-python#415]
Dear maintainers,

Can you please readd the hacktoberfest label? Seems like PRs made to this repo are no longer being counted as a valid repo due to the new opt-in rules this year.

![image](https://user-images.githubusercontent.com/7315217/98058998-ca806480-1e24-11eb-8e5d-99c33e0fef36.png)

After November 15th, all PRs should be accounted by then.

Regards.

**Comment by Chalarangelo** [comment]
Fixed
