### ISSUE TITLE
reverse_number Wrong output

### ISSUE THREAD

**Issue by jumploop** [30-seconds/30-seconds-of-python#442]
![image](https://user-images.githubusercontent.com/38637799/113553861-f9487400-962a-11eb-97cf-eb68176b3514.png)
The output should be of float type
![image](https://user-images.githubusercontent.com/38637799/113553924-11b88e80-962b-11eb-9670-0cca2b73fb24.png)

**Comment by Chalarangelo** [comment]
This isn't a bug, we just trim the decimals in the output.
