### ISSUE TITLE
keys_only implementation

### ISSUE THREAD

**Issue by ahota** [30-seconds/30-seconds-of-python#47]
Dictionaries already have a built-in functions for retrieving only the keys:
```
>>> d
{'a': 97, 'c': 99, 'b': {'i': 105, 'h': 104, 'k': 107, 'j': 106}, 'd': 100}
>>> d.keys()
['a', 'c', 'b', 'd']
```

A loop over the values isn't needed to access them.

**Comment by bsutherland** [comment]
Same is true for `values_only()`..

>>> d.values()

**Comment by xorange** [comment]
Note that Oct 2018 has two issues opened about [keys_only](https://github.com/kriadmin/30-seconds-of-python-code#keys_only)

Solution here seems to be more illustrative and straightforward.

**Comment by Chalarangelo** [comment]
Closing as this seems to have been resolved in the meantime.
