### ISSUE TITLE
average ,there is ambiguity about the functional representation of the second parameter in the function sum 

### ISSUE THREAD

**Issue by carrotshub** [30-seconds/30-seconds-of-python#67]
## [FEATURE] _REPLACE THIS WITH A BRIEF SUMMARY OF THE SUGGESTED SNIPPET_
**Category:** 
### Expected Snippet Behavior

There is ambiguity about the functional representation of the second parameter in the function sum, which should be dealing with floating-point number addition, not floating-point division. And this parameter is not necessary in python3.0. For numeric additions, Python 3.0 automatically converts numeric numbers into more complex numeric types, such as sum([1,2.0]) - 3.0, and / in Python 3.0 must get a floating point result.

**Comment by Chalarangelo** [comment]
Closing as resolved.
