### ISSUE TITLE
[IMPROVEMENT] Definition for lcm is unnecessarily complicated

### ISSUE THREAD

**Issue by havanagrawal** [30-seconds/30-seconds-of-python#89]
### Description

Currently, `lcm` has the following snippet:
```python
from functools import reduce
import math

def spread(arg):
  ret = []
  for i in arg:
    if isinstance(i, list):
      ret.extend(i)
    else:
      ret.append(i)
  return ret

def lcm(*args):
  numbers = []
  numbers.extend(spread(list(args)))

  def _lcm(x, y):
    return int(x * y / math.gcd(x, y))

  return reduce((lambda x, y: _lcm(x, y)), numbers)
```

This is hardly a 30-second snippet, especially if you are looking at it in isolation. Most of the code is tangential to calculating the LCM. It is also an unlikely usage pattern (I don't think anyone expects to use lcm as `lcm([[5, 10], [4, 6, [2]], 8])`). If this were to follow the pattern all other snippets follow, it would probably look like this:

```python3
from math import gcd
from functools import reduce

def lcm(*nums):
  def _lcm(x, y):
    return int(x * y / gcd(x, y))

  return reduce(_lcm, nums)
```

**Comment by Chalarangelo** [comment]
Makes some sense in general, PR it maybe? :+1:

**Comment by Chalarangelo** [comment]
Closing as resolved - although current implementation is a bit more verbose, it allows for some additional use-cases.
